### PR TITLE
Fixed notification in connection with the new header

### PR DESCRIPTION
**Pull request by nikwen**
Previously, the notification was shown at the bottom of the page without any margin. This commit fixes the issue.

### CODE REVIEW

**Comment by nikwen** [comment]
Bump?!

**Comment by iBelieve** [comment]
I've been out of town over the weekend, but I will test this now. Thanks for the pull request! I've been working on designs for Project Dashboard to use the new header, but haven't had a chance to see how the notifications work.

**Comment by nikwen** [comment]
No problem at all. ;)
Have you decided on the pull request yet? It does not change anything when the new header isn't active.

**Comment by nikwen** [comment]
Bump?!

**Comment by iBelieve** [comment]
Works perfectly! Sorry, I totally forgot about reviewing this.

**Comment by nikwen** [comment]
No problem. Thanks for merging.

**Pull request merged**
