### PR TITLE
Added textColor attribute to notifications

### PR DESCRIPTION
**Pull request by nikwen**
The default text color when using a ligth background is a dark grey, so the text is difficult to read.

### CODE REVIEW

**Comment by iBelieve** [comment]
Thanks for the pull request!

Adding `textColor` is great, but it doesn't really solve the problem with the text being dark gray on the black background. Could you also set the default color to `"white"` in the label, so it looks good on all themes?

**Comment by nikwen** [comment]
Sorry, I totally forgot about your comment. I'll change that later. ;)

**Comment by nikwen** [comment]
Ok, finally did it. Sorry for not doing it earlier.

**Comment by iBelieve** [comment]
Looks good! Thanks again.

**Comment by nikwen** [comment]
You're welcome. And thanks for merging. :)

**Pull request merged**
