### PR TITLE
Show notification above keyboard

### PR DESCRIPTION
**Pull request by nikwen**
If the keyboard is visible, the notification is now shown above the keyboard instead of being hidden behind it.

### CODE REVIEW

**Comment by iBelieve** [comment]
How is this affected by `anchorToKeyboard` in `MainView`? I don't have a device to test, but isn't your change only needed when `anchorToKeyboard` is false?

Thanks for the pull request!

**Comment by nikwen** [comment]
I didn't think of that. Will check it tomorrow. Thanks. :)

**Comment by nikwen** [comment]
Ok, you're right. We need to handle that. I'll find a way.

**Comment by nikwen** [comment]
Fixed. ;)

**Comment by iBelieve** [comment]
Looks good, thanks a lot!

**Comment by nikwen** [comment]
Thanks for merging.

**Pull request merged**
